version: "3.7"
services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
        - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - net
    env_file:
      - .env

  fr_sender:
    env_file: .env
    build: fr_sender
    command: /bin/sh /code/entrypoint.sh
    container_name: fr_sender
    restart: unless-stopped
    volumes:
       - static_data:/vol/static
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    expose:
      - "8000"
    depends_on:
      - redis
      - mysql
    networks:
      - net

#  proxy:
#    container_name: proxy
#    restart: unless-stopped
#    build:
#      context: ./proxy
#    volumes:
#      - static_data:/vol/static
#    expose:
#      - "8000"
#    ports:
#      - '8000:8000'
#    networks:
#      - net

  celery_worker:
    build: ./fr_sender/
    container_name: celery_worker
    hostname: celery_worker
    restart: always
    env_file: .env
    command: "celery --app fr_sender worker -l INFO --pool=prefork --concurrency=4 -E"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - fr_sender:/code/fr_sender
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - fr_sender
      - redis
    networks:
      - net

  celery_beat:
    build: ./fr_sender/
    container_name: celery_beat
    hostname: celery_beat
    restart: always
    env_file: .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: "celery --app fr_sender beat -l INFO -s /tmp/celerybeat-schedule"
    volumes:
      - fr_sender:/code/fr_sender
      - /etc/localtime:/etc/localtime:ro
    links:
      - celery-worker
    depends_on:
      - fr_sender
      - redis
    networks:
      - net

  redis:
    container_name: redis
    build:
      context: ./redis
    restart: always
    volumes:
    - ./storage/redis/data:/data
    expose:
      - "6379"
    networks:
      - net

volumes:
  fr_sender:
  static_data:
  mysql_data:

networks:
  net:
    driver: bridge


