# Generated by Django 3.2.8 on 2022-12-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_fr_apimessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fr_apimessage',
            name='sending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
